version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/work
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  logvolume01: {}